language: node_js
node_js:
  - "8.11.2"
  - "9.9.0"
  - "9.10.1"
  - "9.11.1"
  - "10.0.0"
  - "10.1.0"
before_install: npm install -g grunt-cli
install: npm install
notifications:
  email:
    on_success: change
    on_failure: change
